name: originice
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cloud_firestore: 2.5.2
  cupertino_icons: ^1.0.2
  firebase_core: ^1.6.0
  google_fonts: ^2.1.0
  get: ^4.3.8
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/profile.png
  uses-material-design: true

