name: originice
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: 2.5.2
  cupertino_icons: ^1.0.2
  firebase_core: ^1.6.0
  firebase_auth: "^3.1.1"
  firebase_storage: ^10.0.3
  google_fonts: ^2.1.0
  get: ^4.3.8
  flutter:
    sdk: flutter
  flutter_firebase_chat_core: ^1.4.2
  flutter_chat_ui: ^1.4.3
  faker: ^2.0.0
  file_picker: ^4.1.1
  http: ^0.13.3
  image_picker: ^0.8.4+2
  mime: ^1.0.0
  open_file: ^3.2.1
  path_provider: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/profile.png
  uses-material-design: true
